-- drop table TEST_USER;
CREATE TABLE TEST_USER
(
    ID    BIGSERIAL,
    NAME  VARCHAR(40),
    PHONE VARCHAR(40),
    PRIMARY KEY (ID)
);
select * from test_user;
insert into test_user (name, phone,age)
values ('Lynn', '09XXXXXXXX',18);

-- drop table BOOK;
CREATE TABLE BOOK
(
    BOOK_ID      BIGSERIAL,
    BOOK_NAME    VARCHAR(80),
    PUBLISH_TIME TIMESTAMP,
    PRIMARY KEY (BOOK_ID)
);

-- drop table BORROW_BOOK_INFO;
CREATE TABLE BORROW_BOOK_INFO
(
    USER_ID BIGSERIAL,
    BOOK_ID BIGSERIAL,
    PRIMARY KEY (USER_ID, BOOK_ID),
    CONSTRAINT USER_BORROW_FK1 FOREIGN KEY (USER_ID) REFERENCES TEST_USER (ID),
    CONSTRAINT BOOK_BORROW_FK1 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID)
);
SELECT *
FROM BORROW_BOOK_INFO;
